server:
  port: 8080

spring:
  application:
    name: answer-service

  datasource:
    url: "jdbc:mysql://172.16.2.215:3306/heykakaodb"
    username: "heykakao"
    password: "heykakao"
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost

message: "7 message"
