server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: "jdbc:mysql://172.16.2.215:3306/heykakaodb"
    username: "heykakao"
    password: "heykakao"
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://admin:admin@172.16.4.35:8761/eureka/
  instance:
    hostname: localhost

message: "7 message"
