server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://172.16.2.215:3306/user
    username: heykakao
    password: heykakao
    driver-class-name: com.mysql.cj.jdbc.Driver


#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: busrefresh

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://admin:admin@${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: 172.16.4.35

message: "7 message"
