server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://172.16.2.215:3306/heykakaodb
    username: heykakao
    password: heykakao
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 172.16.1.60
      port: 6379
  redis:
    pool:
      max-idle: 5
      min-idle: 0
      max-active: 5
      max-wait: -1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: busrefresh

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://admin:admin@${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: 172.16.4.35

springdoc:
  packagesToScan: heykakao.HeyForm

message: "7 message"
